'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.42.
'
Namespace ozimporthoursService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="to_importSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class to_import
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private timeout_importTimerOperationCompleted As System.Threading.SendOrPostCallback
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "https://outzource.dk/timeout_xp/wwwroot/ver2_1/timereg_net/ozimporthours.asmx"
        End Sub
        
        '''<remarks/>
        Public Event timeout_importTimerCompleted As timeout_importTimerCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/timeout_importTimer", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function timeout_importTimer(ByVal ds As System.Data.DataSet) As String
            Dim results() As Object = Me.Invoke("timeout_importTimer", New Object() {ds})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function Begintimeout_importTimer(ByVal ds As System.Data.DataSet, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("timeout_importTimer", New Object() {ds}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endtimeout_importTimer(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub timeout_importTimerAsync(ByVal ds As System.Data.DataSet)
            Me.timeout_importTimerAsync(ds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub timeout_importTimerAsync(ByVal ds As System.Data.DataSet, ByVal userState As Object)
            If (Me.timeout_importTimerOperationCompleted Is Nothing) Then
                Me.timeout_importTimerOperationCompleted = AddressOf Me.Ontimeout_importTimerOperationCompleted
            End If
            Me.InvokeAsync("timeout_importTimer", New Object() {ds}, Me.timeout_importTimerOperationCompleted, userState)
        End Sub
        
        Private Sub Ontimeout_importTimerOperationCompleted(ByVal arg As Object)
            If (Not (Me.timeout_importTimerCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent timeout_importTimerCompleted(Me, New timeout_importTimerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")>  _
    Public Delegate Sub timeout_importTimerCompletedEventHandler(ByVal sender As Object, ByVal e As timeout_importTimerCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class timeout_importTimerCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
